// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:258043579962:web:c1a5cad5eb7caa8cda2f03',
    messagingSenderId: '258043579962',
    projectId: 'blue-36beb',
    authDomain: 'blue-36beb.firebaseapp.com',
    storageBucket: 'blue-36beb.firebasestorage.app',
    measurementId: 'G-WZ45ZLS53K',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:258043579962:android:33e1f7d6581e7ecdda2f03',
    messagingSenderId: '258043579962',
    projectId: 'blue-36beb',
    storageBucket: 'blue-36beb.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:258043579962:ios:c8a6cb9080a47479da2f03',
    messagingSenderId: '258043579962',
    projectId: 'blue-36beb',
    storageBucket: 'blue-36beb.firebasestorage.app',
    androidClientId: '258043579962-d3jraa6oenn7d4dbas8fk8ps5qosjink.apps.googleusercontent.com',
    iosClientId: '258043579962-je8caobtgo11nftth4ll2k830r6vi7tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.blue',
  );

}